name: Build and push image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get version
        run: |
          VER=$(head -n1 VERSION)
          echo "VERSION=$VER" >>$GITHUB_ENV

      - name: Install qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Build and push with podman
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman build --tag ghcr.io/turscar/hello-world:amd64 --file=Containerfile.amd64 .
          podman build --tag ghcr.io/turscar/hello-world:arm64 --file=Containerfile.arm64 .
          podman manifest create ghcr.io/turscar/hello-world:${{ env.VERSION }}
          podman manifest add ghcr.io/turscar/hello-world:${{ env.VERSION }} ghcr.io/turscar/hello-world:amd64
          podman manifest add ghcr.io/turscar/hello-world:${{ env.VERSION }} ghcr.io/turscar/hello-world:arm64
          podman tag ghcr.io/turscar/hello-world:${{ env.VERSION }} ghcr.io/turscar/hello-world:latest
          podman manifest push --all ghcr.io/turscar/hello-world:${{ env.VERSION }}
